### ISSUE TITLE
Add an option to switch between YM2612 and YM2608 emulation

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/OPNMIDI-Player-Java#1]
Self explanatory - Wohlstand/OPN2BankEditor#46
Currently only OPN2 is available as default.

**Comment by Wohlstand** [comment]
I think, yeah, the ability to switch emulator is nice thing! :fox_face: :+1: 
Thanks for notice!

**Comment by Wohlstand** [comment]
Made just now, please test a thing! :fox_face:

**Comment by papiezak** [comment]
Please correct "MAME YM260**2** OPNA" => it's 2608, YM2602 doesn't exist I think...

It works, although there is something wrong with sample rate, I will examine it when I return from home (maybe I set OPN2 flag instead of OPNA in my bank)

**Comment by Wohlstand** [comment]
Woops, it's a typo, damn

**Comment by Wohlstand** [comment]
Done! https://github.com/Wohlstand/OPNMIDI-Player-Java/commit/f742d6f96e06db6fb70520c4557631d760dfc5d2

**Comment by Wohlstand** [comment]
> It works, although there is something wrong with sample rate, I will examine it when I return from home (maybe I set OPN2 flag instead of OPNA in my bank)

Also be sure to play with disabled "Play at PCM rate" flag

**Comment by papiezak** [comment]
Also I can hear that PMDWIN OPNA handles volumes the different way other OPNa emus do, you can hear distortion, clipping, and noise at times due to high instrument volumes I guess...

**Comment by Wohlstand** [comment]
> Also I can hear that PMDWIN OPNA handles volumes the different way other OPNa emus do, you can hear distortion, clipping, and noise at times due to high instrument volumes I guess...

It's pretty experimental: https://github.com/Wohlstand/libOPNMIDI/pull/86

> @jpcima: On this emulator, I had found a defect in the envelope release.
It's possible that the internal release rate computes as 0, then a keyed-off note will remain forever in release phase, and it will maintain a continuous sound that you can't shut up, except having another note to take over the channel.
I also met suspicious cases of release which took long delays to complete.
It needs a review of the envelope behavior.

**Comment by papiezak** [comment]
Works great, one question before I close it though:
Is it okay that SSG-based instruments are silent? Using the experimental PSG and wavetable branch of bank editor, I made a PSG only instrument and neither of OPNA emus play it.
I thought it will work, given that (Wohlstand/libOPNMIDI#77) was added...

**Comment by Wohlstand** [comment]
PSG support didn't implemented yet on libOPNMIDI yet. I have to implement together with PSG also OPNA rhythm voices too. For that I have experimental branch on OPN2-BE where I made some testing and dirty stuff.

**Comment by Wohlstand** [comment]
As this is complete, so, I closing :fox_face: :+1:
