### ISSUE TITLE
Download for recent versions missing

### ISSUE THREAD

**Issue by IzzySoft** [Wohlstand/OPNMIDI-Player-Java#3]
Similar to https://github.com/Wohlstand/ADLMIDI-Player-Java/issues/7 – here I see Play Store has the recent releases, but your Readme only points to old ones. Can you please add the tags, releases and APKs (at least the latest and future ones)? Thanks!

**Comment by Wohlstand** [comment]
Yeah, the same answer, I working on an update for both players, I work on their stabilization, and all of these I releasing is BETA.

**Comment by Wohlstand** [comment]
P.S. about ReadMe, I just forgot to update it, yeah.

**Comment by IzzySoft** [comment]
Same suggestion then: `pre-release` is a check box you can tick when making a release at Github :wink: But yes, a hint in the ReadMe would certainly help!

**Comment by Wohlstand** [comment]
For everyone's convenience, I made the CI via GitHub Actions that just works. So, even makegh I didn't made any releases, everyone will be able to retrieve the latest auto-built binary at any moment.

**Comment by IzzySoft** [comment]
Thanks! I've told my updater to fetch the pre-releases as well for now (as there was no release for 3 years). From the release notes, it sounds like they are stable enough to be "thrown at the public" :wink:

**Comment by Wohlstand** [comment]
Anyway, there is a problem that on Android 11 they doesn't work as intended because of a freaking file system limitations that overcomplicate things. I need to find a simple example to properly open files on Android 11+ until I can release the new stable version. So, I release it as a beta.
